BEGIN EXECUTE IMMEDIATE 'DROP TABLE audit_salary'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE audit_salary (
  audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id  NUMBER(6),
  old_job_id   VARCHAR2(10),
  new_job_id   VARCHAR2(10),
  old_salary   NUMBER(8,2),
  new_salary   NUMBER(8,2),
  changed_by   VARCHAR2(128),
  changed_on   DATE DEFAULT SYSDATE
);
/
CREATE OR REPLACE TRIGGER trg_salario_en_rango
BEFORE INSERT OR UPDATE OF salary, job_id ON employees
FOR EACH ROW
DECLARE
  vmin jobs.min_salary%TYPE;
  vmax jobs.max_salary%TYPE;
BEGIN
  SELECT min_salary, max_salary INTO vmin, vmax FROM jobs WHERE job_id=:NEW.job_id;
  IF :NEW.salary < vmin OR :NEW.salary > vmax THEN
    RAISE_APPLICATION_ERROR(-20010,'Salario fuera del rango del puesto.');
  END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_audit_salary
AFTER UPDATE OF salary, job_id ON employees
FOR EACH ROW
BEGIN
  INSERT INTO audit_salary(employee_id,old_job_id,new_job_id,old_salary,new_salary,changed_by,changed_on)
  VALUES(:OLD.employee_id,:OLD.job_id,:NEW.job_id,:OLD.salary,:NEW.salary,
         SYS_CONTEXT('USERENV','SESSION_USER'),SYSDATE);
END;
/
